### ISSUE TITLE
No support for MacOS Intel

### ISSUE THREAD

**Issue by quyleanh** [EFForg/apkeep#103]
On MacOS Intel, I cannot running apkeep. It's seems that the system is incompatible.

I try to check the file type of `apkeep-x86_64-unknown-linux-gnu`. The result is:
`./apkeep: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=35477a9ef9fd6a83fdddd94c5dc8bacc97bf2e1f, with debug_info, not stripped`

Could you please support for MacOS Intel? Thank you.

**Comment by asit-fdraschbacher** [comment]
Works fine for me on an Intel MacBook. I installed from crates.io (cargo).

**Comment by Hainish** [comment]
Closing as we do not yet support MacOS for precompiled binaries

**Comment by farstarx** [comment]
Please make a macos darwin support
