### ISSUE TITLE
mention issues and risks in README

### ISSUE THREAD

**Issue by eighthave** [EFForg/apkeep#12]
Hey @Hainish happy to see you all diving into this work :).  Unless you've found a magic bullet, I imagine that the standard issues with Google Play downloaders will also apply here.

*  Google could terminate your Google account based on Terms of Service violations, users should setup burner accounts.
* The session works with a specific "device profile", so only APKs available for that device/location/language/etc will be available
* Paid and DRM apps will not be available.
* Using Tor will might it a lot more likely that the download will fail.

For example, an overview of related issues for Aurora Store are being tracked here: https://gitlab.com/CalyxOS/calyxos/-/issues/613

**Comment by Hainish** [comment]
Thanks @eighthave (and good to hear from you!) - I'll talk to the lawyers here and see how much of this we should include and also if we should add anything else.

**Comment by Hainish** [comment]
By the way, if you're interested in using it for the Aurora Store, `apkeep` is built on top of a library I maintain: https://github.com/EFForg/rs-google-play/tree/master/gpapi.  I could write Android bindings for it using JNI if you'd use it.

**Comment by Hainish** [comment]
These caveats (with a few wording changes) have been added in 42c6a441c2e9d58e1056ae4f5b2db23227a10d27

**Comment by eighthave** [comment]
Sound like someone will be interested in the library.  I personally don't work 
on or use Aurora Store.
