### ISSUE TITLE
Support F-Droid mirrors

### ISSUE THREAD

**Issue by chirayudesai** [EFForg/apkeep#14]
F-Droid supports mirrors.

There are many official mirrors of the f-droid.org repo

https://fdroid.gitlab.io/mirror-monitor/

It would be good if they were supported.

**Comment by Hainish** [comment]
This is supported in fa2d539075e25d1b05d44b4dd68ffec1c41d869c by specifying the mirror, along with the fingerprint, with the `-o` command-line option.

```shell
apkeep -d f-droid -o repo=https://ftp.lysator.liu.se/pub/fdroid/repo?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB -a An.stop .
```

**Comment by Hainish** [comment]
In 9cad87870675746682cbc7c87ded130e7483320e I changed this so that it is not necessary to specify a fingerprint for F-Droid mirrors, it just uses the F-Droid default fingerprint:

```shell
apkeep -d f-droid -o repo=https://ftp.lysator.liu.se/pub/fdroid/repo -a An.stop .
```
