### ISSUE TITLE
Question: apkeep behind http proxy

### ISSUE THREAD

**Issue by U039b** [EFForg/apkeep#141]
Hi,
We, at Exodus Privacy, use apkeep to download apps from Google Play. In some cases, we have to use an HTTP/S proxy for outgoing connections. What is the "good way" to tell apkeep to use a given HTTP/S proxy? Setting both `http_proxy` and `https_proxy` environment variables do not do the trick.

**Comment by U039b** [comment]
Forget about it, `http_proxy` and `https_proxy` environment variables DO the trick.

**Comment by justingoldberg** [comment]
This will work for country lockouts, especialy for rare apps

**Comment by 3052** [comment]
https://github.com/EFForg/apkeep/issues/191

**Comment by 3052** [comment]
no, https_proxy  does not work

**Comment by Hainish** [comment]
I do see this working as well.

**Comment by 3052** [comment]
no, https_proxy does not work
