### ISSUE TITLE
Download app with specific architecture

### ISSUE THREAD

**Issue by kyzsuukii** [EFForg/apkeep#149]
im try to download app but result is app is for `arm64-v8a` and my device is `armv7l (armeabi-v7a)`. its there any way to download app with specific architecture?
if not. its will helpfull for adding options like that.

**Comment by Hainish** [comment]
Yes, though it's a little trickier than just specifying the architecture.  Though not much trickier.

Refer to the top of https://github.com/EFForg/apkeep/blob/master/USAGE-google-play.md specifying a device profile.
