### ISSUE TITLE
apkeep not working on Debian due to missing libssl.so.1.1

### ISSUE THREAD

**Issue by andro-phile** [EFForg/apkeep#178]
## Bug Description

The release binary `apkeep 0.15.0` fails to run on the latest debian stable (debian 12 - bookworm). Apparently due to `libssl1.1` [not being included](https://packages.debian.org/search?keywords=libssl1.1) in debian stable anymore.

It is a bit confusing since apkeep's change log for [0.14.0] - 2022-11-21 already mentions switching to `OpenSSL 3.0.7`.

## Error Message 

`./apkeep-x86_64-unknown-linux-gnu: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

## Related Issues

[#167](https://github.com/EFForg/apkeep/issues/167)

**Comment by andro-phile** [comment]
## Temporary Solution (Compiling Source Code)

As of commit [74c63f8](https://github.com/EFForg/apkeep/commit/74c63f8f967097924efe15f823b194b2c7e6cdec), compiling the source code works fine. I could successfully run `apkeep` and download the `vlc` apk from `apkpure`, `f-droid` and `huawei-app-gallery`. 

## Build Steps

Here are 3 steps to build the `apkeep` binary from Source Code, for Debian Stable (debian 12 - bookworm):

Install missing packages via `apt`. in my case

	sudo apt install curl pkg-config libssl-dev
	
Install [Rust](https://www.rust-lang.org/tools/install), by running

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

Install `apkeep` from the latest commit in this repository

    cargo install --git https://github.com/EFForg/apkeep.git

**Comment by codeurimpulsif** [comment]
@andro-phile have you tested this solution by downloading an APK from the Google Play Store? It compile but it fail with a `Could not log in to Google Play.  Please check your credentials and try again later.` error.

I tried to compile it with the default version of OpenSSL in Debian 12 (`OpenSSL 3.0.11 19 Sep 2023`).

It seems only OpenSSL `1.1.1w` works for the Google Play Store for now.

**Comment by gdimoff** [comment]
any solutions on how to compile with OpenSSL 1.1.1w ? In order to get Google Play Store working

**Comment by Hainish** [comment]
This should work with the latest version of `lib-ssl` in Debian, compiling was successful on our build machine.  Please let me know if problem resurfaces.
