### ISSUE TITLE
Instructions to get ASS token no longer working

### ISSUE THREAD

**Issue by metronidazole** [EFForg/apkeep#189]
The instructions listed no longer work as the google embedded page has been moved.

https://github.com/EFForg/apkeep/blob/master/USAGE-google-play.md

**Comment by johnnymiranda** [comment]
There's currently a PR for this, but this link worked for me. https://accounts.google.com/EmbeddedSetup

**Comment by Hainish** [comment]
Thank you, this issue is resolved by merging #186
