### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by conorgil** [EFForg/apkeep#22]
I ran into an issue where apkeep was hitting its retry loop and reporting that there was an error attempting to download the APK: https://github.com/EFForg/apkeep/blob/fe7afb704e597029339933d3cbff51bd967dc6af/src/main.rs#L165

My teammate tried running to command on his machine and it worked without error. We spent time debugging potential network issues because the text of the error message said that the download had failed.

Turns out that my linux user did not have permission to write to disk in the directory in which I was running apkeep. So, the APK download actually succeeded every time, but it failed to write the file to disk.

It would be great to get some improved error handling to help developers know the specific reason for a failure (download, writing file, reading file, etc).

**Comment by Hainish** [comment]
This should fix the issue with "permission denied": 46090af78a524f3c7b457ff28f509899a2858804

There are other specific error messages for when the file already exists or when there is an invalid app response.  I think this is sufficient for now.

**Comment by kero3009destiny** [comment]
Is there a way to get some verbosity for "Invalid app response" ? Failing to download apps with the response.
