### ISSUE TITLE
Allow downloading previous versions of APKs

### ISSUE THREAD

**Issue by conorgil** [EFForg/apkeep#23]
It would be really great if apkeep allowed me to download a specific version of an APK. For example, if I wanted to download a previous version of an APK to compare its functionality to the latest version available in the Google Play store, I could use APK Pure to download both the legacy version and the current version.

I am thinking something like this:

```
apkeep -a com.someone.something@v1.2.3
```

Where the `@` is the delimiter between the package ID and the desired version to download.

**Comment by Hainish** [comment]
https://github.com/EFForg/apkeep/commit/a2dd25c36148db4c84e94289d53d4ce43579fdd1 adds the ability to download versioned apps on APKPure and F-Droid following the convention you suggest, as well as making it possible in a separate field if you're using a CSV.

It also allows users to look up what versions are available on these sources using the `-l` flag.

Thanks for the suggestion!

**Comment by conorgil** [comment]
Fantastic!! Thanks for the consideration and implementation.
