### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by 89z** [EFForg/apkeep#37]
Dont see any Windows build here:

https://github.com/EFForg/apkeep/releases/tag/0.8.0

**Comment by Hainish** [comment]
Let me see if I can cross-compile it.

**Comment by Hainish** [comment]
Note: https://jake-shadle.github.io/xwin/ from @Jake-Shadle seems like a good way to go.

**Comment by 89z** [comment]
Its a Rust program, why can we just do `cargo build` ...

**Comment by Hainish** [comment]
You can if you don't want to cross-compile.  I'm trying to keep all the compilation steps in one environment.

**Comment by 89z** [comment]
I dont understand what you are talking about. With Go, if you building for Windows on Windows, you do this:

~~~
go build
~~~

If you building for Windows on Linux, you do this:

~~~
GOOS=windows go build
~~~

so whats the problem? Can Rust not do that?

**Comment by Hainish** [comment]
I haven't tried cross-compiling to Windows MSVC before, but it looks like there are a few additional steps involved.

**Comment by Hainish** [comment]
Windows x64 is now supported, available in https://github.com/EFForg/apkeep/releases/tag/0.8.0
