### ISSUE TITLE
Support Huawei AppGallery

### ISSUE THREAD

**Issue by Jean-BaptisteC** [EFForg/apkeep#45]
Add support to dowload apk from [Huawei AppGallery](https://appgallery.huawei.com/)
Idem like Google Play we have need account for download apk

**Comment by ChiefMikeK** [comment]
#80

**Comment by Hainish** [comment]
Added in https://github.com/EFForg/apkeep/commit/7d7ebd11ebfaeaa889b9d67c22fa348656ea81be

**Comment by eighthave** [comment]
This is really great, thanks for this!

**Comment by archon810** [comment]
Sorry to comment on an old thread, but does anyone know if there's an API to view metadata for Huawei App Gallery apps? Perhaps getting metadata could even be added to apkeep if there's interest and a way to do it?

**Comment by Hainish** [comment]
None documented that I know of.  You might try using the Huawei app in combination with something like `mitmproxy` in order to derive an API from the real-time traffic.
