### ISSUE TITLE
Support for APKMirror

### ISSUE THREAD

**Issue by Dhyfer1** [EFForg/apkeep#46]
Both [Aurora Store](https://auroraoss.com/) and [APKMirror](https://www.apkmirror.com/) they are very popular third-party stores. I would like you to add support for both stores. Please.

**Comment by TheLastProject** [comment]
Aurora Store is literally a proxy to the Google Play Store. So Aurora Store support already exists because Google Play Store support exists.

**Comment by asdf8dfafjk** [comment]
@TheLastProject So I just change the URL in the source, rebuild the app and done?

**Comment by TheLastProject** [comment]
No, Aurora Store **is** Google Play Store. There is no different URL. They are 2 apps for the same source.

**Comment by asdf8dfafjk** [comment]
So if aurora is just a frontend for play, I suspect its going to need google credentials as well, and thus not help with #9 ?

**Comment by TheLastProject** [comment]
Aurora Store has an auth token system, but they're very explicit that only Aurora Store is allowed to use it (they had too much abuse of it in the past). So I don't think their system would help you (unless you could somehow convince them to allow apkeep access and apkeep wants to add it)

**Comment by TheLastProject** [comment]
> Sometimes Aurora Store shows available updates of apps that Play Store doesn't show yet

This is because developers on Google Play can do staged rollouts ("make update available to x% of users") and the anonymous account may be part of the randomly chosen x% of users while your regular account isn't. That doesn't make Aurora Store less of a Google Play front-end.

APKMirror indeed is a completely different service.

**Comment by Hainish** [comment]
Last time I looked at the `APKMirror` traffic, it wasn't easily parsable.  I'll have to look at it again and see if it's doable.

**Comment by archon810** [comment]
Hi there, my name is Artem Russakovskii, and I run APKMirror.

While we welcome and collaborate with apps that try to integrate with the site and direct users to our download pages, such as APK Grabber and APK Updater (we can even facilitate an API level collaboration), we don't support integrations that result in leeching our bandwidth while providing nothing in return (such as ad revenue that pays for hosting and bandwidth).

Looking at the usage of this tool (100% command line), I don't see a way to collaborate that would be acceptable to us. 

There is a paid APKMirror Premium membership available, and maybe in the future we could expose a membership key that would allow downloading of a certain number of APKs per day without relying on ad revenue, but that'd be something we'd need to discuss and agree on.

**Comment by Hainish** [comment]
I appreciate your time and response, @archon810.

Looks like there isn't much of a way forward on this.  Closing.
