### ISSUE TITLE
Another app is downloaded

### ISSUE THREAD

**Issue by raffaem** [EFForg/apkeep#51]
I've tried:
```
./apkeep-x86_64-unknown-linux-gnu --app com.a2a.energia .
Downloading com.a2a.energia...
com.a2a.energia downloaded successfully!
```

But the resulting APK contains another app, called "Sportler", instead of the app I want, which is called "MyA2A"

**Comment by Hainish** [comment]
Ack, yeah parsing the results page for an app is a little tricky with APKPure, I'll prioritize looking into this.

**Comment by Hainish** [comment]
@raffaem when I look up this app on APKPure, I get https://apkpure.com/mya2a/com.a2a.energia

Obviously downloading another app is not desirable, but I don't see any APK for this app available on this apps details page.  Are you seeing anything different?

**Comment by Hainish** [comment]
Fixed
