### ISSUE TITLE
Instructions to build after cloning

### ISSUE THREAD

**Issue by raffaem** [EFForg/apkeep#52]
In the README there are instructions to install from latest commit:
```
cargo install --git https://github.com/EFForg/apkeep.git
```

But there is no instructions to build after cloning the repos. That is, I would like to clone the repo, tinker with it and build my modified version.

Can we have those instructions?

I'm not familiar with cargo.

**Comment by Hainish** [comment]
Thank you, added a HACKING.md file in https://github.com/EFForg/apkeep/commit/86c7c9a8bc13332cd33502e03a108e32b878402b
