### ISSUE TITLE
Split apk support

### ISSUE THREAD

**Issue by enovella** [EFForg/apkeep#55]
## Missing Native Libraries
```sh
[10:43 edu@xps tmp] >  apkeep -d GooglePlay -u 'user@gmail.com' -p "password" . -a com.bitso.wallet
Downloading com.bitso.wallet...
com.bitso.wallet downloaded successfully!
[10:43 edu@xps tmp] >  unzip -l com.bitso.wallet.apk |egrep "\.so$"
```

## Installed APK from GooglePlay
```sh
sargo:/data/app/~~1O4T9lFuOfkxiwkYzMdXCA==/com.bitso.wallet-6muMdzgrI_Jlt5TPNIY6-A== # ls -lah
total 26M
drwxrwxr-x 4 system system  3.4K 2022-03-15 09:48 .
drwxrwxr-x 3 system system  3.4K 2022-03-15 09:48 ..
-rw-r--r-- 1 system system   19M 2022-03-15 09:48 base.apk
drwxr-xr-x 3 system system  3.4K 2022-03-15 09:48 lib
drwxrwx--x 3 system install 3.4K 2022-03-15 09:48 oat
-rw-r--r-- 1 system system   32M 2022-03-15 09:48 split_config.arm64_v8a.apk
-rw-r--r-- 1 system system   96K 2022-03-15 09:48 split_config.en.apk
-rw-r--r-- 1 system system  617K 2022-03-15 09:48 split_config.xxhdpi.apk
```

It'd be great to be able to specify the architecture so ARM64 libraries could be downloaded as well. @Hainish

**Comment by Hainish** [comment]
It is possible to specify a device configuration in the latest master, such as an `arm64` device:

```shell
arget/debug/apkeep -a com.bitso.wallet -d google-play -o device=bullhead -u user@gmail.com -p 'password' .
```

This will be in the `0.10.0` release.

The default device (`hero2lte`) is `arm64`.  You can reference the available devices here: https://github.com/EFForg/rs-google-play/blob/master/gpapi/device.properties

**Comment by Hainish** [comment]
Version 0.10.0 has been released: https://github.com/EFForg/apkeep/releases/tag/0.10.0

**Comment by enovella** [comment]
Working even for a tablet app:

```sh
 apkeep -d google-play -u 'xxx@gmail.com' -p "********" -o device=m201 -a ar.tvplayer.tv .
Downloading ar.tvplayer.tv...
ar.tvplayer.tv downloaded successfully!
```

**Comment by Hainish** [comment]
I'm not sure if it's possible to enumerate the available devices for an app with Google Play.  I'm happy to be corrected though.

Seems like this issue is resolved, closing.

**Comment by enovella** [comment]
I meant the ones registered in apkeep with the argument -`o`. Thanks for closing the ticket.
