### ISSUE TITLE
Incorrect usage examples for --download-source

### ISSUE THREAD

**Issue by nsamarin** [EFForg/apkeep#58]
Minor issue, but your documentation states that you should do, e.g.:

`apkeep -a org.mozilla.fennec_fdroid -d f-droid .`

which does not work:

`error: 'f-droid' isn't a valid value for '--download-source <download_source>'`

because the actual names of accepted download-sources are defined as:
```
pub enum DownloadSource {
    APKPure,
    GooglePlay,
    FDroid,
}
```

so the example should be:
`apkeep -a org.mozilla.fennec_fdroid -d FDroid . `

**Comment by Hainish** [comment]
@nsamarin thanks - the documentation is aligned with the latest commit in the repository, but not the latest release.  As of the next release, this will be resolved.

**Comment by Hainish** [comment]
By "resolved" I mean the usage will change to invoke the download source with `f-droid`

**Comment by nsamarin** [comment]
That's great, thank you for the prompt response as well!
