### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by righettod** [EFForg/apkeep#6]
Hi,

First, thanks a lot for this very interesting tool 💯 

Do you plan to provide a binary version for the Windows platforms ?

Thanks a lot in advance for your feedback 👍

**Comment by ehelly** [comment]
I think Windows binaries would be a great addition personally. In the meantime, apkeep can be installed from source pretty easily. First, install [Rust](https://rustup.rs), then run the following in the command line:
`cargo install --git https://github.com/EFForg/apkeep.git`

I don't have a Windows machine to test this on, but I hope this helps!

**Comment by righettod** [comment]
OK thanks you very much 😃

**Comment by Hainish** [comment]
I'd love to know if the tool works on windows.  Any feedback is appreciated!

**Comment by righettod** [comment]
Hi, after several attempts, I did  not achieve to compile it on Windows, i
had issue with OpenSSL.

**Comment by Hainish** [comment]
Dang, sorry it caused you such trouble.  I'll try to cross-compile it for Windows at some point.

**Comment by righettod** [comment]
@Hainish Do not need to worry/apologize, i'm 1000...% sure that the issue come from me because i'm a newbie in Rust 😄
