### ISSUE TITLE
Multi Repository compare feature 

### ISSUE THREAD

**Issue by ChiefMikeK** [EFForg/apkeep#80]
Seeing as this is advertising on EFF as a threat detection,  
and alternative downloads with same `id` ie. Samsung vs Huawei vs Google vs other, ect... are floating around the the net 

There should be an _easier-way_ to compare multiple sources vice only a signature key signed without downloading several apks as I have found a few counterfeit copies around! 

# :shipit: any suggestions on how to?

**Comment by Hainish** [comment]
I think this is a good idea, but out of scope for `apkeep` on its own.  I think a separate project could use `apkeep` as a tool for this purpose, though.
