### ISSUE TITLE
Termux: "libssl.so.1.1" not found

### ISSUE THREAD

**Issue by Generator** [EFForg/apkeep#90]
Unable to execute apkeep v0.12.0 on Termux

```
$ ./apkeep-aarch64-linux-android -h
CANNOT LINK EXECUTABLE "./apkeep-aarch64-linux-android": library "libssl.so.1.1" not found: needed by main executable
$ dpkg -S libssl
openssl-1.1: /data/data/com.termux/files/usr/lib/openssl-1.1/libssl.so.1.1
openssl: /data/data/com.termux/files/usr/lib/pkgconfig/libssl.pc
openssl: /data/data/com.termux/files/usr/lib/libssl.so
openssl: /data/data/com.termux/files/usr/lib/libssl.so.3
openssl-1.1: /data/data/com.termux/files/usr/lib/openssl-1.1/libssl.so
openssl-1.1: /data/data/com.termux/files/usr/lib/openssl-1.1/pkgconfig/libssl.pc
$ uname -a
Linux localhost 4.14.256-QuicksilveR-ginkgo-v2.5/8d0a0c31 #1 SMP PREEMPT Sat Apr 9 00:55:32 PDT 2022 aarch64 Android
```
**Info:**
Android: 12
Termux: 0.118.0
Apkeep: 0.12.0

**Comment by Hainish** [comment]
The `openssl-1.1` package is required, but it looks like it's not listed as a dependency in the package manager.  I'll have to fix that.

For now, to get it running you can run `pkg install openssl-1.1`

**Comment by Hainish** [comment]
If you install `apkeep` from the `termux` repository, does it work?  Does it install any dependencies?

**Comment by Hainish** [comment]
From a fresh `termux` install, if I install `apkeep` from the repository I also have to install `openssl-1.1` but then it works.

**Comment by Hainish** [comment]
I'll add a note in the `README.md` to find it in the `termux` repo.

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/apkeep/commit/d8789ae164b406fbb283f592050c4dc413a91ff9 and [release 0.12.2](https://github.com/EFForg/apkeep/releases/tag/0.12.2).  Downloading a binary from this release will work with all `termux` packages updated to the latest version via `pkg update`.
