### ISSUE TITLE
unable to login on mac mini M1 (apple) chip

### ISSUE THREAD

**Issue by adtimizer** [EFForg/apkeep#96]
Are you able to run this on M1 chip (the google-play store)?

appreciate your tips for that.

**Comment by Hainish** [comment]
We don't compile this for macOS just yet.  I'd have to research how to support it, and if it's possible to cross-compile on Linux.  I don't have a macOS device to test with, unfortunately.

**Comment by adtimizer** [comment]
@Hainish 
on mac with intel chip it works for me. 
if needed i can borrow a mac device on the cloud.

**Comment by adtimizer** [comment]
@Hainish 
Any chance this great library will support linux? it will be an amazing addition to an already great tool.
will provide any linux/test/beer/coffee :-)

**Comment by adtimizer** [comment]
@Hainish 
thanks for getting back. I'm not sure how to run the precompiled libraries.
I've downloaded one of them (arm7 linux ) to my linux machine and tried using the command cargo install <library> but without any luck.
Can you help with instructions for dummies :-)

**Comment by Hainish** [comment]
@adtimizer you may need to install the libssl-1.1 library.
